name: Assets

on:
  push:
    branches: ["main"]

jobs:
  build:
    name: Build and update assets
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4
      - name: Set up Elixir
        uses: erlef/setup-beam@v1.18.0
        with:
          elixir-version: "1.17.3"
          otp-version: "27.1.2"
      - name: Setup project
        run: mix setup
      - name: Push updated assets
        id: push_assets
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Update assets
          file_pattern: dist
